### ISSUE TITLE
Travis + coveralls integration is broken

### ISSUE THREAD

**Issue by djs55** [mirage/shared-block-ring#34]
see #32

**Comment by yomimono** [comment]
[travis is currently green](https://travis-ci.org/mirage/shared-block-ring), but [coveralls hasn't been updated since 2016](https://coveralls.io/github/mirage/shared-block-ring).

**Comment by yomimono** [comment]
`git blame` says I was the last one to touch [this suspicious line](https://github.com/mirage/shared-block-ring/blob/master/.travis.yml#L3), so I'll see about fixing this and otherwise updating the CI setup, which tests some pretty old versions of OCaml.
