### ISSUE TITLE
should we archive this repository?

### ISSUE THREAD

**Issue by yomimono** [mirage/shared-block-ring#54]
In digging into #34 it became clear that there's some bitrot in this repository and it will require a bit of human attention to keep in maintenance.  Before investing that time, I'd like to be sure that this library is used by someone -- if it isn't, I would like to mark it as archived rather than spend time on it.

**Comment by psafont** [comment]
Just in case: this repository is used by https://github.com/xapi-project/message-switch

**Comment by yomimono** [comment]
I'm definitely not going to do anything here, so I'll close this.
